### ISSUE TITLE
Compiler check may not work

### ISSUE THREAD

**Issue by Kwarde666** [Mergevos/samp-logging#1]
I noticed you used this check to check if someone is using the community compiler or not:
```
#if !defined __PawnBuild
	#error I think it's time for you to use community compiler. Get it from https://github.com/pawn-lang/compiler
#endif
```
However, if someone includes samp-logging after including ány YSI include it will not work. YSI Core (which is always included, no matter what YSI include you use) includes y_compilerdata which defines __PawnBuild. You'd better be off using `#if __COMPILER_OFFICIAL` to check if someone is using the stock compiler.
More information about that here: https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Core/y_compilerdata/api.md

**Comment by Mergevos** [comment]
Did you tested, what errors does it give or it simply won't work?

**Comment by Kwarde666** [comment]
Like I said, y_compilerdata (YSI Core) defines "__PawnBuild". So if someone included YSI before samp-logging, it will not return an error when using the stock compiler.
Apart from that it's better to check if __file and __line exist, eg. 
```
#if !defined __file || !defined __line
    #error samp-logging required the community compiler. Get it from github.com/pawn-lang-compiler
#endif
```
You could also just disable the usage of __file and __line if the user's compiler doesn't support it and let people still enter it manually.

**Comment by Mergevos** [comment]
Version 3.0.1 has brought the change in compiler check. I'm started using `#if !defined __file || !defined __line` to check if community compiler is used, I will force developers to use community compiler. Thanks @Kwarde666 for reporting and opening issue. If there's something more you have to say, feel free to contact me via discord. Thanks!
